### PR TITLE
Release notes for v0.3.0

### PR DESCRIPTION
**Pull request by jcvernaleo**

### CODE REVIEW

**Comment by jrick** [comment]
Please add the following known issues to the release notes:

## Known issues

### Paymetheus
- Spendable balance is incorrect and may even go negative after purchasing tickets.  This is only a temporary accounting issue and will resolve itself after the tickets have been mined into a block.

### dcrwallet
- The [WalletService.SpentnessNotifications](https://github.com/decred/dcrwallet/blob/master/rpc/documentation/api.md#spentnessnotifications) gRPC API has been intentionally broken to avoid a deadlock situation.  The RPC will appear to be working but no responses will be streamed to the client.

**Comment by jcvernaleo** [comment]
Known issues added.

**Comment by marcopeereboom** [comment]
ok

**Comment by alexlyp** [comment]
OK if jrick issues were addressed

**Comment by jrick** [comment]
ok

**Pull request merged**
