### PR TITLE
Implement downloadonly flag.

### PR DESCRIPTION
**Pull request by marcopeereboom**
Requested and inspired by:
https://github.com/decred/decred-release/pull/48

### CODE REVIEW

**Comment by jolan** [comment]
It should skip the running checks otherwise it seems kind of useless.

I'd imagine you would want to download and then prep to replace the binaries once downloaded and staged.

**Comment by marcopeereboom** [comment]
It skips the test if it isn't from the official repo.  Basically, this diff does everything identically but just stops after verify.  The magic to set or unset the verify flag is identical.

**Comment by marcopeereboom** [comment]
Ok I misunderstood.  You meant the runtime checks.  I'll add that.

**Comment by jolan** [comment]
Yeah sorry, should have pasted an example like:

```
$ ./dcrinstall -downloadonly
dcrticketbuyer is still running
```

As I said before, this will probably be used to manually download and verify the binaries for an upgrade that will happen at a later time so it should just download the binaries and verify them without checking if processes are running.

**Comment by jolan** [comment]
Works as expected now.

OK

**Comment by jcvernaleo** [comment]
tACK

**Pull request merged**
