### PR TITLE
prep for dex 0.5: always install dex, never download/install bitcoin

### LINKED ISSUE #227: remove bitcoin core download and make --dcrdex enabled by default
Bitcoin Core is not required or even recommended for most users.  Downloading and configuration of it can be removed.

Also, most people just double click the dcrinstall program and this does not run with the `--dcrdex` switch so they don't get DEX support unless they open a console and type in the command with said switch.  We can just have it install dcrdex by default now that the Bitcoin Core stuff is not needed.

### PR DESCRIPTION
**Pull request by chappjc**
Resolves https://github.com/decred/decred-release/issues/227

Our DEX apps will always be installed.  Presumably this was not already the default because of the pesky Bitcoin Core requirement at launch.  It has been quite some time that that has not been needed.  Therefore, this deprecates the `--dcrdex` switch, always installs the dex apps, and never downloads any third party stuff like bitcoind.

This also includes updates to various things like ioutil, removing silly deps, fixing silly go.mod things, updating copyright years, build tags and comments for Go 1.18, etc.

### CODE REVIEW

**Comment by chappjc** [comment]
The exact opposite way to approach this is to entirely remove dex from dcrinstall.

**Comment by chappjc** [comment]
Only draft because I've not had time to test anything, but feel free to review.

**Comment by chappjc** [comment]
Not sure what manifests to update or if https://github.com/decred/release/pull/62 needs to be first.

**Comment by chappjc** [comment]
Tested with via https://github.com/decred/release/pull/62 and dcrinstall.sh with:

`replace github.com/decred/decred-release => github.com/chappjc/decred-release v1.6.0-rc3.0.20220825211652-38a96c47af6d`

**Comment by chappjc** [comment]
Will have to update this for 0.5.1 because Windows is broken in 0.5.0.  Back to draft for the moment

**Review by jrick — APPROVED** [review]

**Comment by chappjc** [comment]
Only tested on linux, and canceled install before creating a LN wallet (but after downloading and extracting dcrd, dcrwallet, and dex stuff).

**Pull request merged**
